export const ADD_FILMS = 'ADD FILMS';
export const ADD_FILM_WITH_DETAILS = 'ADD_FILM_WITH_DETAILS';
export const GET_TEXT_INPUT_VALUE = 'GET_TEXT_INPUT_VALUE';
export const GET_SEARCH_TYPE = 'GET_SEARCH_TYPE';
export const GET_SORT_TYPE = 'GET_SORT_TYPE';
export const CLEAR_TEXT_INPUT_VALUE = 'CLEAR_TEXT_INPUT_VALUE';
